//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuliusSweetland.OptiKey.EyeMine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuliusSweetland.OptiKey.EyeMine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single dynamic keyboard file.
        /// </summary>
        public static string CUSTOM_KEYBOARD_FILE {
            get {
                return ResourceManager.GetString("CUSTOM_KEYBOARD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom folder containing dynamic keyboards.
        /// </summary>
        public static string CUSTOM_KEYBOARDS_FOLDER {
            get {
                return ResourceManager.GetString("CUSTOM_KEYBOARDS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection of built-in Minecraft Keyboards.
        /// </summary>
        public static string EYEMINE_ALL_KEYBOARDS {
            get {
                return ResourceManager.GetString("EYEMINE_ALL_KEYBOARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeMine V2.
        /// </summary>
        public static string EYEMINE_DESCRIPTION {
            get {
                return ResourceManager.GetString("EYEMINE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific EyeMine keyboard.
        /// </summary>
        public static string EYEMINE_SINGLE_KEYBOARD {
            get {
                return ResourceManager.GetString("EYEMINE_SINGLE_KEYBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default location.
        /// </summary>
        public static string RESET_DYNAMIC_KEYBOARD {
            get {
                return ResourceManager.GetString("RESET_DYNAMIC_KEYBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Select folder containing own dynamic XML keyboards&quot;.
        /// </summary>
        public static string SELECT_DYNAMIC_FOLDER_INSTRUCTIONS {
            get {
                return ResourceManager.GetString("SELECT_DYNAMIC_FOLDER_INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SELECT_FOLDER {
            get {
                return ResourceManager.GetString("SELECT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [none set].
        /// </summary>
        public static string STRING_NOT_SET {
            get {
                return ResourceManager.GetString("STRING_NOT_SET", resourceCulture);
            }
        }
    }
}
