//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuliusSweetland.OptiKey.Crayta.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuliusSweetland.OptiKey.Crayta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create copy of built-in keyboards.
        /// </summary>
        public static string COPY_KEYBOARDS {
            get {
                return ResourceManager.GetString("COPY_KEYBOARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single dynamic keyboard file.
        /// </summary>
        public static string CUSTOM_KEYBOARD_FILE {
            get {
                return ResourceManager.GetString("CUSTOM_KEYBOARD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom folder containing dynamic keyboards.
        /// </summary>
        public static string CUSTOM_KEYBOARDS_FOLDER {
            get {
                return ResourceManager.GetString("CUSTOM_KEYBOARDS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying keyboards.
        /// </summary>
        public static string ERROR_COPYING {
            get {
                return ResourceManager.GetString("ERROR_COPYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more keyboards may not have copied correctly..
        /// </summary>
        public static string ERROR_COPYING_DETAILS {
            get {
                return ResourceManager.GetString("ERROR_COPYING_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed sample keyboards.
        /// </summary>
        public static string EYEMINE_ALL_KEYBOARDS {
            get {
                return ResourceManager.GetString("EYEMINE_ALL_KEYBOARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optikey Gaming.
        /// </summary>
        public static string EYEMINE_DESCRIPTION {
            get {
                return ResourceManager.GetString("EYEMINE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single specific keyboard.
        /// </summary>
        public static string EYEMINE_SINGLE_KEYBOARD {
            get {
                return ResourceManager.GetString("EYEMINE_SINGLE_KEYBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick deadzone aspect ratio.
        /// </summary>
        public static string JOYSTICK_ASPECT_RATIO_LABEL {
            get {
                return ResourceManager.GetString("JOYSTICK_ASPECT_RATIO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick horizontal deadzone (% screen).
        /// </summary>
        public static string JOYSTICK_HORZ_DEADZONE_PERCENT_LABEL {
            get {
                return ResourceManager.GetString("JOYSTICK_HORZ_DEADZONE_PERCENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall sound effect volume.
        /// </summary>
        public static string OVERALL_VOLUME {
            get {
                return ResourceManager.GetString("OVERALL_VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default location.
        /// </summary>
        public static string RESET_DYNAMIC_KEYBOARD {
            get {
                return ResourceManager.GetString("RESET_DYNAMIC_KEYBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder containing own dynamic XML keyboards.
        /// </summary>
        public static string SELECT_DYNAMIC_FOLDER_INSTRUCTIONS {
            get {
                return ResourceManager.GetString("SELECT_DYNAMIC_FOLDER_INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing folder.
        /// </summary>
        public static string SELECT_FOLDER {
            get {
                return ResourceManager.GetString("SELECT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination folder.
        /// </summary>
        public static string SELECT_FOLDER_FOR_COPY {
            get {
                return ResourceManager.GetString("SELECT_FOLDER_FOR_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left stick X axis sensitivity.
        /// </summary>
        public static string SENSITIVITY_LEFT_X {
            get {
                return ResourceManager.GetString("SENSITIVITY_LEFT_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left stick Y axis sensitivity.
        /// </summary>
        public static string SENSITIVITY_LEFT_Y {
            get {
                return ResourceManager.GetString("SENSITIVITY_LEFT_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy stick X axis sensitivity.
        /// </summary>
        public static string SENSITIVITY_LEGACY_X {
            get {
                return ResourceManager.GetString("SENSITIVITY_LEGACY_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy stick Y axis sensitivity.
        /// </summary>
        public static string SENSITIVITY_LEGACY_Y {
            get {
                return ResourceManager.GetString("SENSITIVITY_LEGACY_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right stick X axis sensitivity.
        /// </summary>
        public static string SENSITIVITY_RIGHT_X {
            get {
                return ResourceManager.GetString("SENSITIVITY_RIGHT_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right stick Y axis sensitivity.
        /// </summary>
        public static string SENSITIVITY_RIGHT_Y {
            get {
                return ResourceManager.GetString("SENSITIVITY_RIGHT_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [none set].
        /// </summary>
        public static string STRING_NOT_SET {
            get {
                return ResourceManager.GetString("STRING_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string VOLUME {
            get {
                return ResourceManager.GetString("VOLUME", resourceCulture);
            }
        }
    }
}
